name: Generate Documents Index

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'website/documents.json'
      - '.github/**'

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate documents.json
        run: |
          node .github/scripts/generateIndex.js

      - name: Commit and push updated index
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add website/documents.json
          git diff --cached --quiet || git commit -m "🔄 Update documents index"
          git push
